In [11]:
import pandas as pd
import os
from pathlib import Path

# Если файл уже есть на вашем компьютере, просто укажите путь
# Например, если файл лежит в той же папке, что и ноутбук:
#df = pd.read_parquet('housing_residential_processed.parquet')

# Или с полным путем:
df = pd.read_parquet(r"C:\Users\Admin\Downloads\housing_residential_processed.parquet")

print(df.head())

                     address  longitude   latitude  area  room_count  floor  \
0    Коммунистическая, д. 26  37.580768  55.505888  44.7           2      2
1      Рябиновая, д. 3, к. 1  37.424902  55.718709  19.5           0      1
2   Большая Очаковская, д. 3  37.465910  55.688563  61.4           2     18
3  квартал Введенское, д. 1Б  37.617644  55.755819  43.0           2      8
4                      д. 14  37.617644  55.755819  44.0           2      2

   floor_count market_type flat_type  ceiling_height  build_year  balcony  \
0            5   secondary      flat             NaN        <NA>    False
1           15   secondary    studio             NaN        <NA>    False
2           24   secondary      flat             NaN        <NA>    False
3            9   secondary      flat             NaN        <NA>    False
4            5   secondary      flat             NaN        <NA>    False

        price  price_per_square_meter       date
0   3500000.0                 78299.8 2025-06-09
1   6100000.0                312820.5 2025-05-21
2  26000000.0                423452.8 2025-05-06
3   6711000.0                156069.8 2025-05-21
4   3500000.0                 79545.5 2025-06-10

In [13]:
secondary = df[df['market_type'] == 'secondary']
primary = df[df['market_type'] == 'primary']

In [15]:
secondary.describe()

,longitude,latitude,area,room_count,floor,floor_count,ceiling_height,build_year,price,price_per_square_meter,date
count,134056.000000,134056.000000,134056.000000,134043.0,134056.0,126801.0,34998.000000,30136.0,1.340560e+05,1.340560e+05,134056
mean,37.585297,55.732094,54.602626,1.772319,7.503245,13.771595,3.338751,2000.524754,1.170051e+07,2.075042e+05,2025-01-21 19:07:21.701975552
min,36.901462,55.153483,17.500000,0.0,-2.0,0.0,0.000000,0.0,1.100000e+06,4.239100e+03,2010-03-30 00:00:00
25%,37.496650,55.674357,37.400000,1.0,3.0,8.0,2.500000,1990.0,5.900000e+06,1.294414e+05,2025-02-09 00:00:00
50%,37.617644,55.755819,48.500000,2.0,6.0,14.0,2.600000,2013.0,8.500000e+06,1.761167e+05,2025-05-05 00:00:00
75%,37.659919,55.791572,64.800000,2.0,11.0,17.0,2.700000,2021.0,1.300000e+07,2.521059e+05,2025-05-31 00:00:00
max,38.046940,56.040294,877.000000,29.0,73.0,126.0,4150.000000,2027.0,9.143379e+08,2.925373e+06,2025-06-10 00:00:00
std,0.172152,0.111508,28.181256,1.068394,6.019948,7.979173,51.072851,91.16326,1.601763e+07,1.215884e+05,NaN

In [17]:
secondary.info()

<class 'pandas.core.frame.DataFrame'>
Index: 134056 entries, 0 to 134055
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   address                 134056 non-null  string
 1   longitude               134056 non-null  float64
 2   latitude                134056 non-null  float64
 3   area                    134056 non-null  float64
 4   room_count              134043 non-null  Int64
 5   floor                   134056 non-null  Int64
 6   floor_count             126801 non-null  Int64
 7   market_type             134056 non-null  object
 8   flat_type               134056 non-null  string
 9   ceiling_height          34998 non-null   float64
 10  build_year              30136 non-null   Int64
 11  balcony                 134056 non-null  bool
 12  price                   134056 non-null  float64
 13  price_per_square_meter  134056 non-null  float64
 14  date                    134056 non-null  datetime64[ns]
dtypes: Int64(4), bool(1), datetime64[ns](1), float64(6), object(1), string(2)
memory usage: 16.0+ MB

In [16]:
primary.describe()

,longitude,latitude,area,room_count,floor,floor_count,ceiling_height,build_year,price,price_per_square_meter,date
count,1.202347e+06,1.202347e+06,1.202347e+06,1056559.0,1202347.0,0.0,0.0,1202347.0,1.202347e+06,1.202347e+06,1202347
mean,3.757719e+01,5.571471e+01,4.992958e+01,1.701644,10.565979,<NA>,NaN,2020.814646,1.123041e+07,2.142744e+05,2021-05-06 17:58:32.888375040
min,3.691730e+01,5.515900e+01,1.750000e+01,1.0,-2.0,<NA>,NaN,2004.0,1.109000e+06,3.800300e+04,2004-04-25 00:00:00
25%,3.742829e+01,5.560522e+01,3.518000e+01,1.0,5.0,<NA>,NaN,2019.0,5.342867e+06,1.227038e+05,2019-04-09 00:00:00
50%,3.755607e+01,5.570277e+01,4.430000e+01,2.0,9.0,<NA>,NaN,2021.0,7.967080e+06,1.839245e+05,2021-05-20 00:00:00
75%,3.773093e+01,5.581430e+01,6.100000e+01,2.0,14.0,<NA>,NaN,2023.0,1.256283e+07,2.617000e+05,2023-07-31 00:00:00
max,3.804808e+01,5.604984e+01,1.073000e+03,11.0,78.0,<NA>,NaN,2025.0,5.306441e+09,8.925889e+06,2025-08-01 00:00:00
std,2.090946e-01,1.326807e-01,2.255445e+01,0.781026,7.367217,<NA>,NaN,2.483791,1.818583e+07,1.422466e+05,NaN

In [18]:
primary.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1202347 entries, 134056 to 1336402
Data columns (total 15 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   address                 1202347 non-null  string
 1   longitude               1202347 non-null  float64
 2   latitude                1202347 non-null  float64
 3   area                    1202347 non-null  float64
 4   room_count              1056559 non-null  Int64
 5   floor                   1202347 non-null  Int64
 6   floor_count             0 non-null        Int64
 7   market_type             1202347 non-null  object
 8   flat_type               1202347 non-null  string
 9   ceiling_height          0 non-null        float64
 10  build_year              1202347 non-null  Int64
 11  balcony                 1202347 non-null  bool
 12  price                   1202347 non-null  float64
 13  price_per_square_meter  1202347 non-null  float64
 14  date                    1202347 non-null  datetime64[ns]
dtypes: Int64(4), bool(1), datetime64[ns](1), float64(6), object(1), string(2)
memory usage: 143.3+ MB